### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by Arissstoteles** [funkyremi/vscode-google-translate#11]
The plugin stopped working for me - It worked like a charm for 2 days. Since yesterday it doesn't translate at all. VS Code 1.37.1.

**Comment by LeninZapata** [comment]
Hi, the same thing happens to me, I thought it was a conflict with another extensions but it wasn't like that. Reinstall the VSCode without extensions and does not translate anything, the plugin stopped working. Please help

**Comment by funkyremi** [comment]
Sorry guys, the unofficial Google Translate API stopped working due to some Google updates... I just updated the extension that seems to work fine now. The new version is published on the Vscode Marketplace (v1.3.2).
Have a nice day and happy translating 😃

**Comment by LeninZapata** [comment]
Thank you, I will be waiting for this to be resolved soon.

**Comment by funkyremi** [comment]
It is resolved 👍 just update the extension in vscode.

**Comment by LeninZapata** [comment]
This works, thank you very much!

**Comment by Arissstoteles** [comment]
Thanks for the FIX!! 👍👍👍
