### ISSUE TITLE
Translation not working due to 429 status code ("rate limiting")

### ISSUE THREAD

**Issue by SamHuo213** [funkyremi/vscode-google-translate#12]
I ran into a issue with the extension today.  It was not working as expected.  I had to debug the extension to figure out why.

![image](https://user-images.githubusercontent.com/40151580/63973925-a8d95f80-ca60-11e9-86dd-ac250d41309f.png)

This call to the google api is returning a 429 rate limiting error code.  I am guessing it is because the google api used has a limit.  Is it possible to switch to another google api that does not have a limit?

**Comment by SamHuo213** [comment]
Also, I want to suggest having some way for the user to see errors like this in the future without having to debug the extension.  Maybe like a toast?

**Comment by oshliaer** [comment]
I think time has come to add Google Auth for correct using the API.

**Comment by funkyremi** [comment]
If you don't want limits, you need to get a Google Translate API key and pay for the service. For now, you can't set the api key in Vscode Google Translate extension but it would be a nice feature to have. I add it as a new issue (#14)

Regarding the error messages not displayed, I create a new issue too (#13)

I'm running out of time. PR are welcome for both issues.
