### ISSUE TITLE
安装后 键盘。。alt+shift+t 无效啊。。

### ISSUE THREAD

**Issue by shaoyingrui** [funkyremi/vscode-google-translate#21]
安装后 键盘。。alt+shift+t 无效啊。。
按后 出现菜单键。。。

**Comment by funkyremi** [comment]
In english?

**Comment by funkyremi** [comment]
If the shortcut alt+shift+t doesn't work out of the box means that another extension is using this shortcut. You can edit this by opening command palette (CMD+SHIFT+P) then type 'shortcut' and open preferences. You can set your own shortcut for this extension here.
