### ISSUE TITLE
The correct ISO Code of Chinese language

### ISSUE THREAD

**Issue by scarrrr316** [funkyremi/vscode-google-translate#23]
I found that the ISO Code of chinese language provide by https://www.w3schools.com/tags/ref_language_codes.asp cant use，when i input the iso code ，it display an error→zh-Hant/zh/zh-Hans are not supported.
And I search the Language code of google translate API ，the correct code of Chinese are：
![image](https://user-images.githubusercontent.com/43269183/78345489-43d68100-75d0-11ea-8af6-e433e9d763fa.png)

**Comment by funkyremi** [comment]
Would you like to open a PR for this?

**Comment by scarrrr316** [comment]
sorry，I dont know the meaning of PR that you said，emmmm

**Comment by funkyremi** [comment]
A pull request :-)

**Comment by funkyremi** [comment]
I added the traditional language in the new release 1.4.3
