### ISSUE TITLE
Google Translation API issue

### ISSUE THREAD

**Issue by subhamdas88** [funkyremi/vscode-google-translate#26]
Issue Type: <b>Bug</b>

This issue come just after the first start of the Visual code with first translate. 

"Google Translation API issue: Request failed with status code 407"

Extension version: 1.4.3
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by funkyremi** [comment]
Did you setup your proxy configuration?
This error seems to be related to Proxy Authentication.

**Comment by funkyremi** [comment]
I close this issue. Feel free to reopen if needed.
