### ISSUE TITLE
Feature request: "preferred language" setting

### ISSUE THREAD

**Issue by tyler36** [funkyremi/vscode-google-translate#3]
Thank you for the extension. I find it really easy to use.

I like the way the extension places recently translated language at the top of the dropdown list. 
However, when I restart Visual Code, most "recently used" language no longer appears at the top.

This got me thinking. It would be nice to have a "preferred language" setting which automatically adds your "preferred language" to the top.

If your "preferred language" is the same as "recently used" language, there would be no need to display "recently used".

I only ever translate to one language so a simple string setting would be needed. 
EG. "translate.preferred": "ja"

Bonus points:
Additional palette command to translate into preferred language.
EG. "Translate selection(s) to preferred language"

Hmmm, clunky ... Perhaps replace "preferred langauge" with the language name.
EG. 
"translate.preferred": "ja"  =>
"Translate selection(s) to Japanese"

**Comment by funkyremi** [comment]
Thanks for the new feature :-)
I merged it and will deploy it soon.

**Comment by funkyremi** [comment]
version 1.2.0 released 👌

**Comment by tyler36** [comment]
Thank you. 

I recieved the update automatically this morning.  Just a note, I needed to restart VSCode before the settings and command appeared. Not sure if thats something you would like to "force" VS Code to do.
