### ISSUE TITLE
don't work and Key conflict 

### ISSUE THREAD

**Issue by gldegithub** [funkyremi/vscode-google-translate#30]

**Comment by funkyremi** [comment]
Could you please describe your error?

**Comment by gldegithub** [comment]
Even if I turn on the agent, the commands and shortcut keys do not work. No errors are displayed

**Comment by funkyremi** [comment]
Sorry but it seems difficult to debug this issue. It could be a network setting or something else that's causing that. Feel free to reopen if you can get the error logs.
