### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by realdarek** [funkyremi/vscode-google-translate#42]
When I have this plug installed it doesn't work. After selecting text and clicking ALT + SHIFT + T, it doesn't work

**Comment by realdarek** [comment]
help me pls

**Comment by funkyremi** [comment]
If the keyboard shortcut doesn't work for you, you have two options:

- Open the command palette and manually select 'Translate selection(s)'

- Open your keyboard shortcuts, search for 'Translate selection(s)' and set a new shortcut for this command.

**Comment by funkyremi** [comment]
Feel free to reopen if needed
