### ISSUE TITLE
Translation not working due to a HTTP status code 403

### ISSUE THREAD

**Issue by davorpa** [funkyremi/vscode-google-translate#43]
Hi

Since today the translations don't work for me. A 403 error are thrown by Google API.

Some screenshots...

![vscode-translate-1](https://user-images.githubusercontent.com/3125580/97429138-4c4d2b00-1917-11eb-86bb-2663c01a58fe.png)
![vscode-translate-err](https://user-images.githubusercontent.com/3125580/97429142-4e16ee80-1917-11eb-9174-401e08723350.png)

**Environment**:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic snap

**Comment by funkyremi** [comment]
Hello,
Have you tried to setup a proxy?

**Comment by davorpa** [comment]
Hi
Yes, but i really think it's not necesary. What is the reason to setup it permanently on my computer?
Also, error happens intermittently today.

**Comment by funkyremi** [comment]
Hi,
The error you're getting is from the Google Service, it's not related to this extension. This extension is a simple wrapper around an unofficial library that allows to translate using Google service without Google Translate api key.
If you want to use the Google Translate service without error, you can purchase a licence key and use it with an extension that can handle Google Translate api keys.

**Comment by davorpa** [comment]
Good news. Thanks for support.

I suppouse that happens when max limit is reached

I try to research in deep
