### ISSUE TITLE
API issue: connect ETIMEDOUT 172.217.21.78:443 / 216.58.205.78:443

### ISSUE THREAD

**Issue by LoryCave** [funkyremi/vscode-google-translate#44]
I have recently installed this plugin to vscode and, after a short time, it doesen't work anymore.
First it showed the _Request failed with status code 429_ error and now also _connect ETIMEDOUT 172.217.21.78:443_ and _connect ETIMEDOUT 216.58.205.78:443_
Why?

Here some screenshots
![Cattura](https://user-images.githubusercontent.com/50384468/98162507-c6664c80-1ee1-11eb-811c-e6296e106cf2.PNG)
![c](https://user-images.githubusercontent.com/50384468/98162590-e0079400-1ee1-11eb-8635-9c26a455f8cd.png)

**Comment by funkyremi** [comment]
Hello,
It means you made too many request. Try again in few hours.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
