### ISSUE TITLE
Translating complete JSON file as shown in demo gif

### ISSUE THREAD

**Issue by umaqs** [funkyremi/vscode-google-translate#5]
Hi,

First of all, thank you for really amazing work.

I wanted to ask you how can we get the selection of the translation values in the JSON as you have in the demo gif. I tried using regex expressions in "find in the file" to get the group but not sure how to use it to select the text. Is this feature included in your extension, how can I use it? If not, I would be interested in implementing this feature.

I have tried regex like: `[:]\s*"(.+)"`

and then press Alt+Enter to select all the matching. 

![image](https://user-images.githubusercontent.com/7260897/60520943-31948300-9cde-11e9-912f-a8205640486a.png)

But as you can see this matches the value part starting with ":" but I am using capture group to select only the string value.

Perhaps is there a way to select the regex capture group?

Thanks

**Comment by funkyremi** [comment]
Hi @Unitarian 

Happy to see this extension is used by some developers :-).

I think the feature "regex select all capturing group" is not related to the extension itself. The aim of this extension is simply to translate the selected text, the "select" action itself is more related to Vscode or another extension. 

I searched if there's a quick way to do it in Vscode but didn't find anything. Maybe you can open an issue on Vscode repo. 

In the demo, I selected the JSON values manually. Your regex works fine and you can use it even if there are extra characters in it (: and "). I tested and the translation keeps those characters.

Happy coding!

**Comment by umaqs** [comment]
Thank you very much for getting back so quick.

I have quite a large file more than 1000 lines and at some point, I am getting "Error 429 Too Many Requests". 

Is there any workaround?

**Comment by funkyremi** [comment]
When there are too many request, the api may block some of them. This can be improved. It would be awesome if the extension try again multiple times the failed request after a little sleep. If you want you can open an issue and submit a PR for this.
