### ISSUE TITLE
A temporary custom build

### ISSUE THREAD

**Issue by oshliaer** [funkyremi/vscode-google-translate#50]
# Updated

This patch has been merged and published.

You can use the instructions bottom for your own build "as is".

=============

I would like to suggest manual installation [vscode-google-translate-1.4.9-custombuild.vsix] as a temporary alternative to patch #49 for issues #46 #14.

You can build the extension for yourself.

`npm` is required.

```sh
$> git clone --single-branch --branch hot_fix_403 https://github.com/contributorpw/vscode-google-translate.git
$> npm i
$> npm i vsce
$> npx vsce package
```

After that you'll get a `*.vsix` file in the root of the project.

See [Managing Extensions in Visual Studio Code # Install from a VSIX](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

[vscode-google-translate-1.4.9-custombuild.vsix]: https://github.com/contributorpw/vscode-google-translate/blob/hot_fix_403_custombuild/vscode-google-translate-1.4.9-custombuild.vsix

**Comment by funkyremi** [comment]
Thanks, I published version 1.4.10 🤝
