### ISSUE TITLE
  i cant use it

### ISSUE THREAD

**Issue by renjiancheng** [funkyremi/vscode-google-translate#53]
Google Translation API issue: connect ETIMEDOUT *********

**Comment by funkyremi** [comment]
Can you please try it behind a proxy?

**Comment by renjiancheng** [comment]
the problem is i can use it A few months ago, without proxy

**Comment by funkyremi** [comment]
Can you provide the steps to reproduce the issue?

**Comment by renjiancheng** [comment]
After I install the plugin, select the target statement or word and the plugin will start translating. After the plugin timeout, vscode will receive the above event.Repeatably uninstall and reinstall vscode or plugins

**Comment by funkyremi** [comment]
Ok thank you. I can’t reproduce it so I think it seems like a network issue. Try with a proxy and let me know.

**Comment by renjiancheng** [comment]
I think it's me. I'm sorry. I'll figure something out for myself
