### ISSUE TITLE
Google Responded with 302

### ISSUE THREAD

**Issue by No3371** [funkyremi/vscode-google-translate#55]
I accidentally sent tremendous amount of requests by mass selection with regex then got blocked by google, guess I hit the rate limit.

Not complaining or asking for help, just worrying if this will affect other users of this plugin like maybe all users are sharing the quota 😅

**Comment by funkyremi** [comment]
Hey :-) Thanks for your message!
Don't worry the rates are by IP address.
Enjoy!
