### ISSUE TITLE
multiple lines and only the right part in quotes

### ISSUE THREAD

**Issue by Loranrix** [funkyremi/vscode-google-translate#57]
Hi,
how do you do on your video to select multiple lines and only the right part in quotes?
thanks

**Comment by funkyremi** [comment]
Hello,
I made it manually. You can use ctrl+d to select next occurence multiple times if you have the same pattern on multiple lines. For example in json you can select ´ »: « ´ and then play with ctrl+shift+ -> to select until the end of line.

**Comment by Loranrix** [comment]
ok thanks
