### ISSUE TITLE
NOT CAPABLE TO CONVERT ENGLISH TO PUNJABI LANGUAGE

### ISSUE THREAD

**Issue by kamleshwebtech** [funkyremi/vscode-google-translate#67]
I HAVE CHANGED THE SETTINGS TO CONVERT STRINGS TO PUNJABI LANGUAGE BUT IT IS NOT CONVERTING GIVEN TEXT TO PUNJABI LANGUAGE IN VS CODE EDITOR. IT GOT STUCK ON LAST CONVERTED LANGUAGE. I HAVE CHANGE THE SETTINGS MANY TIMES, RESTARTED VS CODE MANY TIMES AFTER CHANGING LANGUAGE IN PLUGIN, UNINSTALLED AND RE-INSTALLED 2-3 TIMES THEN RESTARTED VS CODE BUT ISSUE IS STILL PERSIST. KINDLY TAKE CARE THIS ISSUE AND FIX THIS ISSUE. THANKS A LOT TO DEV TEAM.

**Comment by funkyremi** [comment]
Seems to work on my side. Try translating behind a proxy.
