### ISSUE TITLE
Feature: Submit in smaller packets.

### ISSUE THREAD

**Issue by YpsilonTM** [funkyremi/vscode-google-translate#70]
When does one use a plugin like this, the moment he has to translate a lot of things. But for me for example if I use it I always get a timeout because it is probably to much.

**Comment by funkyremi** [comment]
Good idea :-)

**Comment by YpsilonTM** [comment]
Not sure if this ever will be implemented but I' going through al my issues and this one seems to have been dead so I am going to close it.
