### ISSUE TITLE
Translate arrays

### ISSUE THREAD

**Issue by erperejildo** [funkyremi/vscode-google-translate#73]
When I want to translate this:
```
"team_names": [
    {
      "name": "Cats",
      "avatar": "cat"
    },
    {
      "name": "Dogs",
      "avatar": "dog"
    },
]
```
I get this:
```
"team_names": {
    "0": {
      "name": "Gatos",
      "avatar": "cat"
    },
    "1": {
      "name": "Perros",
      "avatar": "dog"
    },
]
```

This breaks some logic in my app. How could I get a normal array like the first one, just translating the names?

**Comment by funkyremi** [comment]
Hey :-)
This extension is not intended to translate code but text. You can select only the text with multiple cursors and translate.
Hope this helps.

**Comment by erperejildo** [comment]
so why does it changes the structure then?
