### ISSUE TITLE
Default language settings keeps getting set

### ISSUE THREAD

**Issue by daanpape** [funkyremi/vscode-google-translate#74]
Hello,

I have just installed your extension version 1.4.13 in vscode and I experience an issue. I would like to select my language every time that I press `Alt+Shift+T`. For me this only works once, as soon as I have translated something the `vscodeGoogleTranslate.preferredLanguage` gets set and it never asks me the language choice again.

Is there any way to prevent this?

Kind regards,
Daan

**Comment by funkyremi** [comment]
I think you're using the command "Translate selection to preferred language" instead of "Translate selection"
Try changing your keyboard shortcut to call the second one.

**Comment by Ashark** [comment]
I was looking for the same. Thanks.
Can you please specify that in readme?
