### ISSUE TITLE
Add proxy support?

### ISSUE THREAD

**Issue by wybert** [funkyremi/vscode-google-translate#9]
It's cool tools. But sometimes it can not work because of the network.  Add proxy support would be AWESOME:)

**Comment by funkyremi** [comment]
Do you want to make a PR for that?

**Comment by wybert** [comment]
Nope. The google translator is prohibited in some regions. The only way is to use proxy.

**Comment by funkyremi** [comment]
Ok, I'll have a look a it when I have some free time. 
You could use it with a VPN until it's available in the extension.

Note: https://github.com/hua1995116/google-translate-open-api/issues/2#event-2613747501

**Comment by funkyremi** [comment]
Feature available in new release 1.4.0 👍
